flyway_root: /opt/flyway
flyway_version: 4.2.0
database:
  dbms: oracle
  name: icsopft
  address: "csdb5001.test.vocalink.co.uk"
  username: "FT3_ICSCORE"
  password: "Password123-"
  port: "1522"
schemas: FT3_ICSAQ
flyway_table: schema_history
