# volume properties

ipsbase:        "/opt/ips"
ipsbasesize:    "2097152"
ipsdata:        "/var/ips/data"
ipsdatasize:    "10485760"
ipslog:         "/var/ips/log"
ipslogsize:     "10485760"
ipsarch:        "/var/ips/archive"
ipsarchsize:    "10485760"
