---
- name: create external ics-ips-connector-application properties
  template:
    src=../templates/ics-ips-connector-application.j2
    dest="{{  wls_domain_config['core'].ips_connector_props }}"
    owner="{{ deploy_user }}"
    group="{{ deploy_group }}"
    mode="0644"
