---

- name: create external ics-core-application  properties
  template:
    src=../templates/ics-core-application.j2
    dest="{{ wls_domain_config['core'].core_ext_props }}"
    owner="{{ deploy_user }}"
    group="{{ deploy_group }}"
    mode="0644"

