---

- name: create external ips-stub properties
  template:
    src=../templates/ips-stub.j2
    dest="{{  wls_domain_config['core'].ips_stub_props }}"
    owner="{{ deploy_user }}"
    group="{{ deploy_group }}"
    mode="0644"
