#Apps home where nexus downloads
domain_application_home: '/fs01/release/devops'

# Directory where the scripts for the WebLogic lifecycle are placed
scripts_directory: '{{ domain_application_home }}/scripts'

#Directory where external properties are kept in SIT1
core_props_dir: '/fs01/release/devops/properties/stC01'
bo_props_dir: '/fs01/release/devops/properties/stC11'
settlement_props_dir: '/fs01/release/devops/properties/stC21'
access_props_dir: '/fs01/release/devops/properties/stC31'
portal_props_dir: '/fs01/release/devops/properties/stC41'
#ips_bo_props_dir: '/fs01/release/devops/properties/stC51'

# keystore location
keystore_type: "jks"
keysore_location: "/fs01/app/bea/keystores/trust_newbacs.jks"

# WLS Deployment  user and group
deploy_user: 'devops'
deploy_group: 'devops'

# Software and configuration main directory
oracle_base: '/fs01/app/sw'

# JDK installer and target folder
jdk_folder: '{{ oracle_base }}/jdk1.8/jdk1.8.0_102'
java_home: '{{ jdk_folder }}'
java: "{{ jdk_folder }}/bin/java"
domain_configuration_home: ''
configuration_home: ''
weblogic_base_dir: '/fs01/app/sw/wls12.1.3'

wls_domain_config:
    core:
      env_script_sh: '{{ scripts_directory }}/coreEnv.sh'
      deploy_artifacts_py: '{{ scripts_directory }}/core_deploy.py'
      domain_props: '{{ scripts_directory }}/core_domain.properties'
      deploy_script_sh: '{{ scripts_directory }}/core_deploy.sh'
      runtime_home: '{{ weblogic_base_dir }}/stC01_icscore'
      domain_name: 'stC01_icscore'
      stub_props: '{{domain_application_home}}/properties/stC01/ips-stub.properties'
      middleware_home: '{{ weblogic_base_dir }}/stC01_icscore'
      weblogic_home: '{{ weblogic_base_dir }}/stC01_icscore/wlserver'
      wlst_sh: '{{ weblogic_base_dir }}/stC01_icscore/wlserver/common/bin/wlst.sh'
      wlsenv_sh: '{{ weblogic_base_dir }}/stC01_icscore/wlserver/server/bin/setWLSEnv.sh'
      mserver_start_py: '{{ scripts_directory }}/core_mserver_start.py'
      mserver_stop_py: '{{ scripts_directory }}/core_mserver_stop.py'
      mserver_start_sh: '{{ scripts_directory }}/core_mserver_start.sh'
      mserver_stop_sh: '{{ scripts_directory }}/core_mserver_stop.sh'
      core_ext_props: '{{domain_application_home}}/properties/stC01/ics-core-application.properties'
      ips_connector_props: '{{domain_application_home}}/properties/stC01/ics-ips-connector-application.properties'
      ips_stub_props: '{{domain_application_home}}/properties/stC01/ips-stub.properties'
      stub_logback_props: '{{domain_application_home}}/properties/stC01/logback_ips-stub.xml'
      core_mq_props: '{{domain_application_home}}/properties/stC01/mq-settings.properties'
      file_connector_logback_xml: '{{domain_application_home}}/properties/stC01/ics-ips-connector/logback_default.xml'
    access:
      env_script_sh: '{{ scripts_directory }}/accessEnv.sh'
      deploy_artifacts_py: '{{ scripts_directory }}/access_deploy.py'
      domain_props: '{{ scripts_directory }}/access_domain.properties'
      deploy_script_sh: '{{ scripts_directory }}/access_deploy.sh'
      runtime_home: '{{ weblogic_base_dir }}/stC31_icsaccess'
      domain_name: 'stC31_icsaccess'
      middleware_home: '{{ weblogic_base_dir }}/stC31_icsaccess'
      weblogic_home: '{{ weblogic_base_dir }}/stC31_icsaccess/wlserver'
      wlst_sh: '{{ weblogic_base_dir }}/stC31_icsaccess/wlserver/common/bin/wlst.sh'
      wlsenv_sh: '{{ weblogic_base_dir }}/stC31_icsaccess/wlserver/server/bin/setWLSEnv.sh'
      mserver_start_py: '{{ scripts_directory }}/access_mserver_start.py'
      mserver_stop_py: '{{ scripts_directory }}/access_mserver_stop.py'
      mserver_start_sh: '{{ scripts_directory }}/access_mserver_start.sh'
      mserver_stop_sh: '{{ scripts_directory }}/access_mserver_stop.sh'
      access_ext_props: '{{domain_application_home}}/properties/stC31/ics-access-application.properties'
      file_ext_props: '{{domain_application_home}}/properties/stC31/ics-file-connector-application.properties'
    bo:
      env_script_sh: '{{ scripts_directory }}/boEnv.sh'
      deploy_artifacts_py: '{{ scripts_directory }}/bo_deploy.py'
      domain_props: '{{ scripts_directory }}/bo_domain.properties'
      deploy_script_sh: '{{ scripts_directory }}/bo_deploy.sh'
      runtime_home: '{{ weblogic_base_dir }}/stC11_icsbo'
      domain_name: 'stC11_icsbo'
      middleware_home: '{{ weblogic_base_dir }}/stC11_icsbo'
      weblogic_home: '{{ weblogic_base_dir }}/stC11_icsbo/wlserver'
      wlst_sh: '{{ weblogic_base_dir }}/stC11_icsbo/wlserver/common/bin/wlst.sh'
      wlsenv_sh: '{{ weblogic_base_dir }}/stC11_icsbo/wlserver/server/bin/setWLSEnv.sh'
      mserver_start_py: '{{ scripts_directory }}/bo_mserver_start.py'
      mserver_stop_py: '{{ scripts_directory }}/bo_mserver_stop.py'
      mserver_start_sh: '{{ scripts_directory }}/bo_mserver_start.sh'
      mserver_stop_sh: '{{ scripts_directory }}/bo_mserver_stop.sh'
      bo_ext_props: '{{domain_application_home}}/properties/stC11/ics-backoffice.properties'
      bo_ref_ext_props: '{{domain_application_home}}/properties/stC11/ics-external-refdata.properties'
    portal:
      env_script_sh: '{{ scripts_directory }}/portalEnv.sh'
      deploy_artifacts_py: '{{ scripts_directory }}/portal_deploy.py'
      domain_props: '{{ scripts_directory }}/portal_domain.properties'
      deploy_script_sh: '{{ scripts_directory }}/portal_deploy.sh'
      runtime_home: '{{ weblogic_base_dir }}/stC41_icsportal'
      domain_name: 'stC41_icsportal'
      middleware_home: '{{ weblogic_base_dir }}/stC41_icsportal'
      weblogic_home: '{{ weblogic_base_dir }}/stC41_icsportal/wlserver'
      wlst_sh: '{{ weblogic_base_dir }}/stC41_icsportal/wlserver/common/bin/wlst.sh'
      wlsenv_sh: '{{ weblogic_base_dir }}/stC41_icsportal/wlserver/server/bin/setWLSEnv.sh'
      mserver_start_py: '{{ scripts_directory }}/portal_mserver_start.py'
      mserver_stop_py: '{{ scripts_directory }}/portal_mserver_stop.py'
      mserver_start_sh: '{{ scripts_directory }}/portal_mserver_start.sh'
      mserver_stop_sh: '{{ scripts_directory }}/portal_mserver_stop.sh'
      portal_ext_props: '{{domain_application_home}}/properties/stC41/ics-portal-web-app.properties'
    settlement:
      env_script_sh: '{{ scripts_directory }}/settlementEnv.sh'
      deploy_artifacts_py: '{{ scripts_directory }}/settlement_deploy.py'
      domain_props: '{{ scripts_directory }}/settlement_domain.properties'
      deploy_script_sh: '{{ scripts_directory }}/settlement_deploy.sh'
      runtime_home: '{{ weblogic_base_dir }}/stC21_icssettlement'
      domain_name: 'stC21_icssettlement'
      middleware_home: '{{ weblogic_base_dir }}/stC21_icssettlement'
      weblogic_home: '{{ weblogic_base_dir }}/stC21_icssettlement/wlserver'
      wlst_sh: '{{ weblogic_base_dir }}/stC21_icssettlement/wlserver/common/bin/wlst.sh'
      wlsenv_sh: '{{ weblogic_base_dir }}/stC21_icssettlement/wlserver/server/bin/setWLSEnv.sh'
      mserver_start_py: '{{ scripts_directory }}/settlement_mserver_start.py'
      mserver_stop_py: '{{ scripts_directory }}/settlement_mserver_stop.py'
      mserver_start_sh: '{{ scripts_directory }}/settlement_mserver_start.sh'
      mserver_stop_sh: '{{ scripts_directory }}/settlement_mserver_stop.sh'
      ss_props: '{{domain_application_home}}/properties/stC21/signature-service.properties'
      ezsign_props: '{{domain_application_home}}/properties/stC21/ezsign.properties'
      ics_idp_props: '{{domain_application_home}}/properties/stC21/ics-idp.properties'
      logback_props: '{{domain_application_home}}/properties/stC21/logback_signature-service.xml'
    gateway:
      env_script_sh: '{{ scripts_directory }}/coreEnv.sh'
      deploy_artifacts_py: '{{ scripts_directory }}/core_deploy.py'
      domain_props: '{{ scripts_directory }}/core_domain.properties'
      deploy_script_sh: '{{ scripts_directory }}/core_deploy.sh'
      runtime_home: '{{ weblogic_base_dir }}/stC01_icscore'
      domain_name: 'stC01_icscore'
      middleware_home: '{{ weblogic_base_dir }}/stC01_icscore'
      weblogic_home: '{{ weblogic_base_dir }}/stC01_icscore/wlserver'
      wlst_sh: '{{ weblogic_base_dir }}/stC01_icscore/wlserver/common/bin/wlst.sh'
      wlsenv_sh: '{{ weblogic_base_dir }}/stC01_icscore/wlserver/server/bin/setWLSEnv.sh'
      mserver_start_py: '{{ scripts_directory }}/core_mserver_start.py'
      mserver_stop_py: '{{ scripts_directory }}/core_mserver_stop.py'
      mserver_start_sh: '{{ scripts_directory }}/core_mserver_start.sh'
      mserver_stop_sh: '{{ scripts_directory }}/core_mserver_stop.sh'
      #gateway_props: '{{domain_application_home}}/properties/stC01/ics-ips-gateway/config-ips-gateway/ics-ips-gateway-{{ gateway }}/gateway.properties'
      #snmp_props: '{{domain_application_home}}/properties/stC01/ics-ips-gateway/config-ips-gateway/ics-ips-gateway-{{ gateway }}/snmp.properties'
      #bankgateway_xml: '{{domain_application_home}}/properties/stC01/ics-ips-gateway/config-ips-gateway/ics-ips-gateway-{{ gateway }}/bankgateway-config.xml'
      #dsp_props: '{{domain_application_home}}/properties/stC01/ics-ips-gateway/config-ips-gateway/ics-ips-gateway-{{ gateway }}/dsp.properties'
      #log4j_xml: '{{domain_application_home}}/properties/stC01/ics-ips-gateway/config-ips-gateway/ics-ips-gateway-{{ gateway }}/log4j.xml'
    sws:
      env_script_sh: '{{ scripts_directory }}/swsEnv.sh'
      deploy_artifacts_py: '{{ scripts_directory }}/sws_deploy.py'
      domain_props: '{{ scripts_directory }}/sws_domain.properties'
      deploy_script_sh: '{{ scripts_directory }}/sws_deploy.sh'
      runtime_home: '{{ weblogic_base_dir }}/stC51_icsipsbo'
      domain_name: 'stC51_icsipsbo'
      middleware_home: '{{ weblogic_base_dir }}/stC51_icsipsbo'
      weblogic_home: '{{ weblogic_base_dir }}/stC51_icsipsbo/wlserver'
      wlst_sh: '{{ weblogic_base_dir }}/stC51_icsipsbo/wlserver/common/bin/wlst.sh'
      wlsenv_sh: '{{ weblogic_base_dir }}/stC51_icsipsbo/wlserver/server/bin/setWLSEnv.sh'
      mserver_start_py: '{{ scripts_directory }}/settlement_mserver_start.py'
      mserver_stop_py: '{{ scripts_directory }}/settlement_mserver_stop.py'
      mserver_start_sh: '{{ scripts_directory }}/settlement_mserver_start.sh'
      mserver_stop_sh: '{{ scripts_directory }}/settlement_mserver_stop.sh'
