---

- name: create ics deploy script
  template:
    src=../templates/ics_deploy_script.j2
    dest="{{ wls_domain_config[domain].deploy_script_sh }}"
    owner="{{ deploy_user }}"
    group="{{ deploy_group }}"
    mode="0644"

