---
- name: Test local host
  
  hosts: weblogic
  user: a1704
  connection: local
  gather_facts: yes
  vars_files:
    # variables for infrastructure
    - ../inv/test/group_vars/all/config/env_props.yml
    - ../inv/test/group_vars/all/config/wls_props.yml

  roles:
#    - role: ../roles/ics_build_fix
    - role: ../roles/ics_config
