---
- name: download artifact from nexus 
  hosts: localhost
  connection: local
  roles: 
     - { role: roles/gateway_common }
     - { role: roles/ics-download-artifacts }
     - { role: roles/nexus-download, domain: 'gateway' }
