
- name: configure target  host
  
  hosts: ics_core
  user: devops
  gather_facts: yes

  roles:
    - role: roles/ics_build_fix
    - {role: roles/config_gateway_100001_properties, domain: 'gateway', gateway: '{{ gateway }}'}
