
- name: configure target  host
  hosts: ics_core
  user: devops
  gather_facts: yes
#  vars_files:
    # variables for infrastructure
#    - {{ inventory }}/group_vars/all/config/env_props.yml
#    - ../inv/stC01/group_vars/all/config/wls_props.yml

  roles:
    #- role: roles/ics_build_fix
    - role: roles/ics_config
